DEFAULT_FONT_FAMILY = ""  # empty -> system default sans-serif
DEFAULT_FONT_SIZE = 0  # 0 -> system default size
DEFAULT_LINE_HEIGHT = 1.6
DEFAULT_WORD_WRAP = True
DEFAULT_SHOW_LINE_NUMBERS = False
DEFAULT_SPELL_CHECK = True
DEFAULT_THEME = "system"
DEFAULT_AUTOSAVE_INTERVAL_MS = 30_000
