DEFAULT_FONT_FAMILY = ""  # empty -> system default sans-serif
DEFAULT_FONT_SIZE = 0  # 0 -> system default size
DEFAULT_LINE_HEIGHT = 1.6
DEFAULT_WORD_WRAP = True
DEFAULT_SHOW_LINE_NUMBERS = False
DEFAULT_GECTOR_MODEL = "letheviet/gector-roberta-base-5k-onnx"
DEFAULT_GECTOR_MODEL_DIR = ""  # empty = not configured
DEFAULT_THEME = "system"
DEFAULT_TYPING_SOUNDS = True
DEFAULT_TYPING_SOUND_PACK = "alpaca"
DEFAULT_AUTOSAVE_INTERVAL_MS = 30_000

DEFAULT_STICKER_REWARDS = False
DEFAULT_STICKER_FOLDER = ""
